plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.8'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'org.soso'
version = '0.0.1-SNAPSHOT'
description = 'ledger'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}


repositories {
	maven { url 'https://maven.aliyun.com/repository/public' }
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-websocket'
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'
	compileOnly 'org.projectlombok:lombok'
	runtimeOnly 'com.mysql:mysql-connector-j'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
	testCompileOnly 'org.projectlombok:lombok'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testAnnotationProcessor 'org.projectlombok:lombok'
	implementation 'com.baomidou:mybatis-plus-spring-boot4-starter:3.5.16'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.security:spring-security-crypto'
	implementation 'io.jsonwebtoken:jjwt-api:0.13.0'
	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.13.0'
	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.13.0'
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'
	implementation platform("com.baomidou:mybatis-plus-bom:3.5.16")
	implementation "com.baomidou:mybatis-plus-jsqlparser"
	implementation 'org.springframework.boot:spring-boot-starter-json'

}

tasks.named('test') {
	useJUnitPlatform()
}
