# multipart 1MB
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# dev
spring.profiles.active=dev

# ================= ?????? =================
logging.level.root=INFO
logging.level.org.soso.ledger=DEBUG
logging.file.name=logs/ledger-app.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n

